apiVersion: v1
kind: Secret
metadata:
    name: seafile-secret
type: Opaque
stringData:
    SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:lVYWwUoeejSIPYkKc+EuyA==,iv:bhZqM07WO/7Xhhrj1Kwp4VzFvrDEactWAtfsdJTjl3o=,tag:Hb5/xS5elUOMUuw9B3rbsA==,type:str]
    SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:2UaJOaMMvYyl9z84ntMg,iv:+oef4o/U29PBDayah3ZCb/mOx3RT4pR7Uuo6ZIqTFq4=,tag:H+q0M6OlyAucuVO+je+UgA==,type:str]
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:XsGheju9Rpw=,iv:+q9+v7MpDiRpUxHdderR4HYbHHnMEuFM7rElwDF5L4E=,tag:3bVqT7hhs5f9W7Xcne+akA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:EGrYPRj1EvLeS7s=,iv:E3k88cIKcCaY+dLe4So7Yb3PDFgohczWfu92BAcfQgE=,tag:btnpiNUwwkl09nXQ95y6gQ==,type:str]
sops:
    age:
        - recipient: age1gdpzd8s8q0nj0efj4te224przkk4qyy4xj6l42ffms39gjg3396s42njea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR3FpbHoxV2tYTE54NFJk
            MDRMc1BCd3pFbm9GUXdHNHNHZERaa1BWWnhvCmwrejNPeGwxK0Qvd2hldzJ0NXdW
            UXZNZ2lKbmVUL0NVT1Rwb1Y4ekxnNk0KLS0tIHBDR1VaWWdnampqQnE2S0N3Y0VX
            QWNSazZ1N0hJSUpVOEFYMStPemluY0UKo0+pJRkPPFAts6hwti/1SzKMOterLarB
            7JizPbG3g7xG5+MqULIzsLG2lA1HCZ/1r9bQQFsFvqURoIExqh6EAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T08:00:52Z"
    mac: ENC[AES256_GCM,data:b8Oq13eHFbGwV6xO+q+CQd9Yw/Pp32RP24bLNGe7mnbD4Q2o7CWOv7Y7PLRocSbkuTYOf6HZ2YjwIDwHRv2VCl1GTkRQ1CqpMW6LO4ebh0vLhBcEks/LaFndaF2EnVIYawxLj8LlZEp893jkGUFXHtCFLHjbaxuNP8PGUezAAOM=,iv:hZWtLz9k0UNHdDq9NV7PxEW4/3ZOC0rQDD/jSukhuew=,tag:CCmnrqhcGGCndP7SKqyhMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
