apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mariadb_storage.yaml
  - mariadb_deployment.yaml
  - mariadb_service.yaml
  - seafile_storage.yaml
  - seafile_deplyment.yaml
  - seafile_service.yaml
