apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seafile
  namespace: seafile
spec:
  interval: 5m
  chart:
    spec:
      chart: seafile
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: seafile
        namespace: flux-system

  values:
    # Flux will automatically read values.yaml from the same directory

