apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:13.0.21
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_USER
              value: seafile
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: DB_PASSWORD
            - name: DB_ROOT_PASSWD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: DB_ROOT_PASSWORD
            - name: SEAFILE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_ADMIN_EMAIL
            - name: SEAFILE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_ADMIN_PASSWORD
            - name: SEAFILE_SERVER_HOSTNAME
              value: seafile.local
          ports:
            - containerPort: 80
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data

