apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:n9z1bICEDSKXDDsM1RSPqA+awSvL6f91C5OJD0DEv/7m509LJ9aNYN5fW6lf309uRnJ3mUS9ONM7zbgs2gBSTAT2diG/zMNE11rRPNCEPKbSebFVzdlTGbeQBGmlZ0E4QtMyKi1sqP3rafhY5ybz0faxLBrTmancO7okdkmqk5wYoUfIyXJkHWUhGz/7N/x836zsapziiEHIH+fjFiO/lyBBISjz0dyNX43c9SG8zuf8fo9kKMUDzUAnsSTWXwOkYsVrdYFy2NfSiSQrzLeWU/pCnOXuCpzlAYgVYlOpNsVnU2/Tol9TNpzn3Qk=,iv:YGgZuzQTNAOmju7AEpQprhDrtwVuZLF55CkMM+G1pwk=,tag:6E265n5nfvnEZry/p4o9ng==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1gdpzd8s8q0nj0efj4te224przkk4qyy4xj6l42ffms39gjg3396s42njea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WXp4bVlNT2hlK1orZ3pl
            dXZaVVVwYkdQeklVNUhRSm5sUmU1Tml4U1RJClp3TXFEOUtsUGVFQmR2NW4vU1lw
            cG1WMTBKb0NoZFlnbkNyTDIwQUlVM0EKLS0tIEVLWGJyTVNLRStTUlBkUWlFS2Mz
            bTJHMTREbncwNWdBUC9iemZiUS9RQ1kKjtkSfEfBWfGUlsBtUItr19Dlis8NaBU2
            HqNfQOGzs+n7rTwv1QRYSxLCXlkE4Yb72mfEZp8XyKPsFIBAn8qHXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T13:15:29Z"
    mac: ENC[AES256_GCM,data:zQ3F3Ep1uJCuWt8Sk6pmpvLCB5ATq+5jF94ARLJ2esLm5MYwHOJJCysX/OIiUTDoltJHytaUI54OIH7QNYWc+rcbT8eu9tK3OscoY2JwQbSVb5tDxsec09WPuXGArCcHDl9ugLXzrvKiKon48pGsq2l2uHAtBS/4U/17vH4X2vw=,iv:UMZlypLufcyNO1hAW0ELWplG4hAi0gjljpWss6jRdmo=,tag:lrMIqxe7IUopsgS091P4uA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
