apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
type: Opaque
stringData:
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:ygSqImTC9lh9,iv:SYb/mPTipWeYouZ6SjnsjP4qngwBlOZTcbMGyvVsYFg=,tag:6Yy5RH0DV9hcu/LXuPwSuA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:u9a75v5ysu8lJ4255J4=,iv:U5S+Bz/OJKDnMpjbr3J0YRg0ogiMn/IVXAy2jtoMV3U=,tag:wONioyUq1uMEHK7Cv9AhQg==,type:str]
sops:
    age:
        - recipient: age1gdpzd8s8q0nj0efj4te224przkk4qyy4xj6l42ffms39gjg3396s42njea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSVZDaElmem1KZnVmWFNt
            aWFHNFlPcHNIQ0xWTzNtdWsyUmFWZVpFaVV3ClgzNXRkMUJjbWtYT2ZjUW5QOEFK
            eWJjMHlVbUxQMG4weVdXR2RxdGlmUmcKLS0tIFVNZ1FZZ1hyTjU3V0ZVZ3V5bGJa
            YnVsaU9mR0ZYQkZ5TC91UnFJenRjd1EKgl0qFfCh4n+br4oweQcXBqEyHy+68TuM
            akfFZkWO+GQ5d9xnFOv35IGqdQbKrKzqQNH44+im98NFe++n9zvCxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:06:01Z"
    mac: ENC[AES256_GCM,data:jwzsJSGtjQccpZ+DqF13DWFNQrmBKL2StXk5RktMShj/DxHK4rOWQlZxz74Ekpq/wfsNHdEsn/T0cksjl6JcMHdZRmsz+kUGOzvuTz3gQteNZsAT2vG2N32FEVE8LX6XSktnmxEY5axVDqUCcOWnu5zu/aV2yPcRs/ddKV9hzK8=,iv:Ktht9rWXoEKJ8Tfuz87sza/Th/+aeh4PVcp+59d4eVY=,tag:FICUm0U6HnUjIgaCTC98tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
