apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mariadb_deployment.yaml
  - mariadb_service.yaml
  - nextcloud_deployment.yaml
  - nextcloud_service.yaml
#  - storage.yaml
#  - configmap.yaml
