apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-mariadb
  template:
    metadata:
      labels:
        app: nextcloud-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:12
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: nextcloud-db-pvc
